### ISSUE TITLE
ScheduledTasks.json format error

### ISSUE THREAD

**Issue by ierdelyi** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#212]
Hi,

The [ScheduledTasks.json] format is wrong. Please modify it!
(https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/main/2009/ConfigurationFiles/ScheduledTasks.json)

   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeList(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
ConvertFrom-Json : Invalid JSON primitive: .
+ ... ist = (Get-Content $ScheduledTasksFilePath | ConvertFrom-Json).Where( ..
At C:\optimize\Virtual-Desktop-Optimization-Tool-main\Windows_VDOT.ps1:277 char:68

**Comment by tmmuessig** [comment]
I've reverted the changes
